import type { ThemeConfig } from 'antd';
import { theme } from 'antd';

/** BearReader warm-paper theme: quiet, flat and typography-led. */
export const appTheme: ThemeConfig = {
  algorithm: theme.defaultAlgorithm,
  token: {
    colorPrimary: '#171717',
    colorInfo: '#53677A',
    colorSuccess: '#51705A',
    colorWarning: '#967238',
    colorError: '#9A514A',
    colorBgLayout: '#FAFAF7',
    colorBgContainer: '#FFFFFF',
    colorBgElevated: '#FFFFFF',
    colorBgSpotlight: '#171717',
    colorFillSecondary: '#F1F1EE',
    colorFillTertiary: '#F6F6F2',
    colorFillQuaternary: '#FAFAF7',
    colorText: '#171717',
    colorTextSecondary: '#686868',
    colorTextTertiary: '#8A8A84',
    colorTextQuaternary: '#A6A6A0',
    colorTextPlaceholder: '#8A8A84',
    colorBorder: '#A6A6A0',
    colorBorderSecondary: '#D8D8D4',
    borderRadius: 2,
    borderRadiusLG: 4,
    boxShadow: 'none',
    boxShadowSecondary: '0 12px 32px rgba(23, 23, 23, 0.14)',
    controlHeight: 40,
    controlOutline: '#171717',
    fontFamily:
      "'Microsoft YaHei', 'PingFang SC', 'Noto Sans CJK SC', system-ui, sans-serif",
    lineHeight: 1.65,
  },
  components: {
    Layout: {
      bodyBg: '#FAFAF7',
      siderBg: '#FFFFFF',
      headerBg: '#FAFAF7',
    },
    Card: {
      colorBgContainer: '#FFFFFF',
      colorBorderSecondary: '#D8D8D4',
      boxShadowTertiary: 'none',
    },
    Menu: {
      iconSize: 17,
      collapsedIconSize: 17,
      itemBg: '#FFFFFF',
      itemColor: '#686868',
      itemHoverBg: '#F1F1EE',
      itemHoverColor: '#171717',
      itemSelectedBg: '#E8E8E4',
      itemSelectedColor: '#171717',
      groupTitleColor: '#8A8A84',
      subMenuItemBg: '#FFFFFF',
      popupBg: '#FFFFFF',
      itemBorderRadius: 2,
    },
    Button: {
      defaultBg: '#FFFFFF',
      defaultBorderColor: '#A6A6A0',
      defaultColor: '#171717',
      defaultHoverBg: '#F1F1EE',
      defaultHoverBorderColor: '#171717',
      defaultHoverColor: '#171717',
      primaryShadow: 'none',
      fontWeight: 500,
    },
    Input: {
      colorBgContainer: '#FFFFFF',
      colorBorder: '#A6A6A0',
      activeBorderColor: '#171717',
      hoverBorderColor: '#686868',
      activeShadow: '0 0 0 2px rgba(23, 23, 23, 0.08)',
    },
    InputNumber: {
      colorBgContainer: '#FFFFFF',
      colorBorder: '#A6A6A0',
      activeBorderColor: '#171717',
      hoverBorderColor: '#686868',
    },
    Select: {
      colorBgContainer: '#FFFFFF',
      colorBorder: '#A6A6A0',
      activeBorderColor: '#171717',
      hoverBorderColor: '#686868',
      optionSelectedBg: '#E8E8E4',
      optionSelectedColor: '#171717',
      selectorBg: '#FFFFFF',
    },
    Tabs: {
      itemColor: '#686868',
      itemHoverColor: '#171717',
      itemSelectedColor: '#171717',
      inkBarColor: '#171717',
    },
    Progress: {
      defaultColor: '#53677A',
      remainingColor: '#E8E8E4',
    },
    Tag: { marginXS: 0, defaultBg: '#F1F1EE', defaultColor: '#686868' },
    Typography: {
      colorLink: '#171717',
      colorLinkHover: '#686868',
      colorLinkActive: '#171717',
    },
    Table: {
      headerBg: '#F1F1EE',
      headerColor: '#686868',
      borderColor: '#D8D8D4',
      rowHoverBg: '#F6F6F2',
    },
    Modal: { contentBg: '#FFFFFF', headerBg: '#FFFFFF' },
    Drawer: { colorBgElevated: '#FFFFFF' },
    Notification: { colorBgElevated: '#FFFFFF' },
    Dropdown: { colorBgElevated: '#FFFFFF' },
    Tooltip: { colorBgSpotlight: '#171717' },
    Pagination: { itemBg: '#FFFFFF', itemActiveBg: '#E8E8E4' },
    Empty: { colorTextDescription: '#8A8A84' },
  },
};
