"""Add EPUB import sessions

Revision ID: f82e926fe785
Revises: 064c024aa744
Create Date: 2026-09-01 14:40:55.832581
"""

from typing import Sequence, Union

from alembic import op
import sqlmodel as sa
from sqlmodel.sql.sqltypes import AutoString

# revision identifiers, used by Alembic.
revision: str = "f82e926fe785"
down_revision: Union[str, Sequence[str], None] = "064c024aa744"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

try:
    dialect = op.get_context().dialect.name
except Exception:
    dialect = ""


def upgrade() -> None:
    """Upgrade schema."""
    # SQLite databases are managed by the model-fingerprint sync path
    # (services/db.py _sync_sqlite_schema), which already creates this
    # table; running the DDL here would fail on "table already exists".
    if dialect == "sqlite":
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import_sessions",
        sa.Column("id", AutoString(), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.Column("extra", sa.JSON(), nullable=False),
        sa.Column("user_id", AutoString(), nullable=False),
        sa.Column("analyze_job_id", AutoString(), nullable=True),
        sa.Column("commit_job_id", AutoString(), nullable=True),
        sa.Column("novel_id", AutoString(), nullable=True),
        sa.Column("file_sha256", AutoString(), nullable=False),
        sa.Column("original_name", AutoString(), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("staging_path", AutoString(), nullable=False),
        sa.Column("status", AutoString(), nullable=False),
        sa.Column("error", AutoString(), nullable=True),
        sa.Column("preview", sa.JSON(), nullable=False),
        sa.Column("expires_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["analyze_job_id"], ["jobs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["commit_job_id"], ["jobs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("import_sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_import_sessions_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_import_sessions_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_import_sessions_updated_at"), ["updated_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_import_sessions_user_id"), ["user_id"], unique=False)
        batch_op.create_index("ix_import_sessions_user_status", ["user_id", "status"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    if dialect == "sqlite":
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("import_sessions", schema=None) as batch_op:
        batch_op.drop_index("ix_import_sessions_user_status")
        batch_op.drop_index(batch_op.f("ix_import_sessions_user_id"))
        batch_op.drop_index(batch_op.f("ix_import_sessions_updated_at"))
        batch_op.drop_index(batch_op.f("ix_import_sessions_status"))
        batch_op.drop_index(batch_op.f("ix_import_sessions_created_at"))

    op.drop_table("import_sessions")
    # ### end Alembic commands ###
